management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  server:
    port: 7778

server:
  port: 7778

spring:
  application:
    name: blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: Hyq0901.
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&useSSl=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
logging:
  pattern:
    #日志格式
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) - %clr([%t]){faint} %X{log_id} %clr(%logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p - [%t] %X{log_id} %logger{39} : %m%n%wEx"
  file:
    path: src/main/resources/log
    name: "%d{yyyy-MM-dd HH:mm:ss.SSS}-log.txt"
    max-history: 7
    max-size: 20MB
    total-size-cap: 1GB
    clean-history-on-start: false
  level:
    root: info
