management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  server:
    port: 7778

server:
  port: 8090

spring:
  application:
    name: blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: alan0901
    url: jdbc:mysql://182.92.65.196:3306/alandb?characterEncoding=utf-8&useSSl=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: alandb
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    root: info
  file:
    path: src/main/resources/log
    name: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n%l'
    max-history: 7
    max-size: 20MB
    total-size-cap: 1GB
    clean-history-on-start: false
