management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'

spring:
  profiles:
    active: dev
  application:
    name: graduation-project
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    #将默认的存储引擎切换为InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #再日志中打印出执行的sql语句
    show-sql: true
    #指明在程序启动的时候要删除并且创建的实体类的表
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern:
      - classpath:/static/**
  resources:
    static-locations:
      - classpath:/META-INF/resoures/
      - classpath:/resoures/
      - classpath:/static/
      - classpath:/public/
  sqltoy:
    # 多个路径用逗号分隔(这里要注意是路径,sqltoy会自动向下寻找以sql.xml结尾的文件,不要写成classpath:com/**/*.sql.xml)
    sqlResourcesDir: classpath:com/sqltoy/quickstart
    # 默认值为classpath:sqltoy-translate.xml，一致则可以不用设置
    translateConfig: classpath:sqltoy-translate.xml
    # 默认开启跨数据库函数自动适配(如oracle的nvl,当数据库切到mysql时会自动替换成ifnull)
    #functionConverts: default
    # 默认为false，debug模式将打印执行sql,并自动检测sql文件更新并重新加载
    debug: true
    # 提供统一字段:createBy createTime updateBy updateTime 等字段补漏性(为空时)赋值(可选配置)
    unifyFieldsHandler: com.sqltoy.plugins.SqlToyUnifyFieldsHandler
    # sql执行超过多长时间则进行日志输出,用于监控哪些慢sql(可选配置:默认30秒)
    printSqlTimeoutMillis: 300000
    # 数据库保留字兼容处理(原则上不要使用数据库保留字,多个用逗号分隔)
    #reservedWords: maxvalue,minvalue
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.alan.blog.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl